PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
SELECT ?class count(*) 
WHERE 
{GRAPH ?g
{
?s rdf:type ?class .
filter (isuri($s))
}
}
GROUP BY ?class
