PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?s ?p ?o ?type_s ?type_o ?source_s ?source_o
WHERE 
{
  GRAPH ?source_s
  {
	?s ?p ?o.
	?s rdf:type ?type_s .
  }
  filter( isuri(?s) )
  filter( isuri(?o) )
  GRAPH ?source_o
  {
	?o rdf:type ?type_o .
  }
  filter( ?source_s!=?source_o )
}
limit 100