PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?subject ?class ?source
WHERE 
{
  ?class rdfs:subClassOf <http://inference-web.org/2.0/pml-provenance.owl#Person>.
  GRAPH ?source
  {
	?subject rdf:type ?class .
  }
}
