PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT distinct ?id ?label ?url ?class ?team ?source
WHERE 
{
  ?class rdfs:subClassOf <http://inference-web.org/2.0/pml-provenance.owl#Agent>.
  GRAPH ?source
  {
	?id rdf:type ?class .
	?id <http://inference-web.org/2.0/pml-provenance.owl#hasName> ?label.
	?id ?p1 _:x .
	_:x  <http://inference-web.org/2.0/pml-provenance.owl#hasURL> ?url .   

  }
  GRAPH ?source1
  {
	optional{
		?team ?p ?id.
		?team rdf:type <http://inference-web.org/2.0/pml-provenance.owl#Organization> .

	}
  }
}
