PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?subject ?p1 ?p2 ?o ?source
WHERE 
{
  GRAPH ?source
  {
        {
	?subject ?p1 _:x .
	_:x ?p2 ?o .
        filter( regex(str(?o), "smith","i"))
        }
        union
        {
	?subject ?p1 ?o .
        filter( regex(str(?o), "smith","i"))
        }
        filter(isuri(?subject))
  }
}
