PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX pmlj:     <http://inference-web.org/2.0/pml-justification.owl#>
PREFIX pmlr:     <http://inference-web.org/2.0/pml-relation.owl#> 
PREFIX pmlp:     <http://inference-web.org/2.0/pml-provenance.owl#>
PREFIX owl:      <http://www.w3.org/2002/07/owl#>

CONSTRUCT
{ ?i_1 owl:sameAs ?i_2 .
}
WHERE
{
?ns_1 owl:sameAs ?ns_2.
?ns_1 pmlj:hasConclusion ?i_1.
?ns_2 pmlj:hasConclusion ?i_2.
}
